### ISSUE TITLE
what functionality is ready to try / test out

### ISSUE THREAD

**Issue by RYAN-dot-LOCAL** [ChrisCates/CommonCrawler#15] opened 2019-05-08 14:26 UTC
The readme says coming soon..., are any of the go programs ready for folks to try out today?

**Comment by ChrisCates** [comment] 2019-05-08 14:32
Hi @4688-is-great,

You can actually just run `go run src/*.go` and it should work as intended.
Currently, it is stable on Mac OS and Linux.

If you want to modify the parameters for crawling, you'll have to do it manually by updating the `config.go` file.

**Comment by ChrisCates** [comment] 2019-05-08 14:44
Feel free to open issues in regards to feedback. Will be closing this for now.

**Closed as completed by ChrisCates** 2019-05-08 14:44 UTC
